# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XoSoVietlott' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XoSoVietlott
  pod 'lottie-ios'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'BaseComponentKit', path: './Frameworks/BaseComponentKit'
  
end
